{
        "name" : "Gestion de production",
        "version" : "1.0",
        "author" : "Adib Regaieg",
        "website" : "http://",
        "category" : "Unknown",
        "description": """  """,
        "depends" : [
					'base',
					'mail',
					'email_template',
					'web',
					'jasper_reports',
					'web_kanban',
					'web_widget_datepicker_options',
					'web_one2many_kanban',
					'one2many_sorted',
					'web_m2x_options',#Add new options for many2one field
					],
		"demo_xml" : [ ],
		'qweb': ['static/src/xml/template.xml'], 
		"data" : [
				'security/production_security.xml',
				'security/ir.model.access.csv',
				'wizard/production_article_change_qte_view.xml',
				'wizard/piece_rechange_change_stock_view.xml',
				'wizard/planifier_intervention_view.xml',
				'wizard/traiter_intervention_interne_view.xml',
				'wizard/traiter_intervention_externe_view.xml',
				'wizard/select_famille_view.xml',
				'views/production.xml',
				'production_data.xml',
				'vente_data.xml',
				'achat_data.xml',
				'maintenance_data.xml',
				'production_report.xml',
				'vente_view.xml',
				'production_view.xml',
				'achat_view.xml',
				'partenaire_view.xml',
				'maintenance_view.xml',
				'maintenance_report.xml',
				],
		"init_xml": [],
		"installable": True
}
